### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by cadri20** [medievalghoul/simplekernel#1]
When I compile de kernel with "make" it throws an error because when linking there are multiple "exception_messages" definitions

**Comment by wizardengineer** [comment]
> When I compile de kernel with "make" it throws an error because when linking there are multiple "exception_messages" definitions

That is strange. I didn't have no issues compiling; however, I'll make sure attempt compilation again when I'm able too.

**Comment by cadri20** [comment]
Do I have to compile it with CMake maybe? Can you write de commands to compile it please, I didn't see a tutorial in the README

**Comment by wizardengineer** [comment]
I'll make sure to add the commands, the CMake wasn't meant to be used per se. As I haven't finish it yet
